# Generated by Django 3.2.7 on 2022-06-03 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20220602_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='upload.file')),
            ],
        ),
    ]
